# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 18:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_friend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friend',
        ),
    ]
